---
#Setup Default Apps

# Create Namaspace
- name: Create a k8s namespace
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl create ns {{ apps_namespace }} 

# Add MongoDB
- name: Create mongodb Deployment by reading the definition from a local file
  template: src=mongodb.yml.j2 dest=/tmp/mongodb.yml

# Add Node app
- name: Create App Deployment by reading the definition from a local file
  template: src=nodeapp.yml.j2 dest=/tmp/app.yml

# Apply the mongodb manifests
- name: Apply the mongodb manifests
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f /tmp/mongodb.yml -n {{ apps_namespace }}

# Apply the app manifests
- name: Apply the app manifests
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f /tmp/app.yml -n {{ apps_namespace }}